[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["mongodb"]


[dev]
  command = "pnpm run dev"   # your vite dev command
  port = 8888                # port netlify dev exposes
  targetPort = 5173          # port vite runs on internally
  framework = "vite"